name: Build and Deploy
run-name: ${{ github.actor }} is no-more testing GitHub Actions
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ONESIGNAL_APP_ID: "mytestid"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to Github Pages
        env:
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Print ONESIGNAL_APP_ID
        run: echo "Hello $ONESIGNAL_APP_ID or $ONESIGNAL_APP_ID2"
        env:
          ONESIGNAL_APP_ID2: ${{ secrets.ONESIGNAL_APP_ID }}
